name: PR Build (Java 21)

on:
  pull_request:
    branches: [ main, "update" ]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build-and-verify:
    name: build-and-verify
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 21 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Maven Verify (tests + checkstyle)
        run: mvn -B -ntp clean verify

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install lizard
        run: pip install --disable-pip-version-check --no-input lizard

      - name: Run lizard on main Lambda file only (Java)
        run: |
          # Check only the main Java handler file and fail on warnings
          # -C: cyclomatic complexity threshold (warn if function > 10)
          # -L: maximum function length (lines) threshold (warn if function > 120)
          lizard -l java -C 10 -L 120 src/main/java/concurrencyeval/Handler.java
